import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import dts from "vite-plugin-dts";
import path from "node:path";

const name = "v-clipboard";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    dts({
      insertTypesEntry: true,
      outputDir: "dist/types",
    }),
  ],
  build: {
    lib: {
      name,
      entry: path.resolve(__dirname, "src/index.ts"),
      formats: ["es", "umd"], // adding 'umd' requires globals set to every external module
      fileName: (format) => `${name}.${format}.js`,
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: ["vue"], // not every external has a global
      output: {
        sourcemap: true,
        // disable warning on src/index.ts using both default and named export
        exports: "named",
        // Provide global variables to use in the UMD build
        // for externalized deps (not useful if 'umd' is not in lib.formats)
        globals: {
          vue: "Vue",
        },
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
});
